In [1]:
import numpy as np

In [2]:
arr = np.array([1,'a',True])
arr

array(['1', 'a', 'True'], dtype='<U11')

In [3]:
for ele in arr:
    print(type(ele))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [5]:
arr[0]

array([1, 2])

In [6]:
arr[-1][-1]

4

In [7]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
 arr.shape

(2, 3)

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr = np.array([1,2,3,4], dtype='int8')
arr

array([1, 2, 3, 4], dtype=int8)

In [11]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [12]:
ones = np.ones([4,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
empty = np.empty(5)
empty

array([0., 0., 0., 0., 0.])

In [14]:
myrange = np.arange(6)
myrange

array([0, 1, 2, 3, 4, 5])

In [15]:
arr = np.arange(2,10,2)
arr

array([2, 4, 6, 8])

In [16]:
arr = np.linspace(0,10, num=5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.sort([7,86,5,54,6,4,78,67,1,9,23])

array([ 1,  4,  5,  6,  7,  9, 23, 54, 67, 78, 86])

In [18]:
arr_a = np.array([5,6,7,8])
arr_b = np.array([1,2,3,4])
np.concatenate((arr_a,arr_b))

array([5, 6, 7, 8, 1, 2, 3, 4])

In [19]:
arr_a = np.array([[1,2],[3,4]])
arr_b = np.array([[5,6],[7,8]])
#arr_c = np.array([[9,10],[11,12]])
np.concatenate((arr_a, arr_b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [20]:
arr_b.ndim

2

In [21]:
ones = np.ones((3,2,3))
ones.ndim

3

In [22]:
ones.size

18

In [23]:
ones.shape

(3, 2, 3)

In [24]:
arr = np.array(['a','b','c','d','e','f'])
arr

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [25]:
arr.reshape(3,2)

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [26]:
arr.reshape(2,3)

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [27]:
# also by passing np.reshape()
np.reshape(arr, newshape=(1,3,2))

array([[['a', 'b'],
        ['c', 'd'],
        ['e', 'f']]], dtype='<U1')

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [29]:
arr.shape

(6,)

In [30]:
arr2 = arr[np.newaxis, :]
arr

array([1, 2, 3, 4, 5, 6])

In [31]:
arr2.shape

(1, 6)

In [32]:
arr3 = arr[:, np.newaxis]
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [37]:
arr3.shape

(6, 1)

In [34]:
arr_4 = np.expand_dims(arr, axis=0)
arr_4

array([[1, 2, 3, 4, 5, 6]])

In [35]:
arr_5 = np.expand_dims(arr, axis=1)
arr_5

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
arr_4.shape

(1, 6)

In [43]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
arr[arr > 5] #pass condition inside 

array([6, 7, 8, 9])

In [47]:
even_no = arr[arr  % 2 == 0]
arr[even_no]

array([0, 2, 4, 6, 8])

In [48]:
even = (arr % 2 == 0) & (arr != 0)
even

array([False, False,  True, False,  True, False,  True, False,  True,
       False])

In [49]:
arr[even]

array([2, 4, 6, 8])

In [51]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,0,1,3]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 3]])

In [53]:
mask = np.nonzero(arr > 3)
mask

(array([0, 1, 1, 1, 1, 2], dtype=int64),
 array([3, 0, 1, 2, 3, 0], dtype=int64))

In [54]:
arr[mask]

array([4, 5, 6, 7, 8, 9])

In [55]:
arr1 = [[1,1],[3,3]]
arr2 = [[2,2],[4,4]]


In [57]:
np.hstack((arr1,arr2))

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [59]:
np.vstack((arr1,arr2))

array([[1, 1],
       [3, 3],
       [2, 2],
       [4, 4]])

In [60]:
arr = np.arange(1,13).reshape(2,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [61]:
np.hsplit(arr,3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [62]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 + arr2

array([5, 7, 9])

In [63]:
arr2 - arr1

array([3, 3, 3])

In [64]:
arr1 * arr2

array([ 4, 10, 18])

In [65]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [67]:
arr1.mean()

2.0

In [68]:
rand = np.random.default_rng()
rand.random(5)

array([0.13224657, 0.06831226, 0.93680596, 0.69698132, 0.1454097 ])

In [70]:
rand.random((4,2))

array([[0.86618155, 0.38875121],
       [0.0752282 , 0.79137753],
       [0.72176056, 0.07842885],
       [0.19100687, 0.44455213]])

In [82]:
rand.integers(low=1, high=5, size=(4,6))

array([[1, 1, 2, 1, 4, 3],
       [1, 1, 4, 3, 4, 3],
       [2, 3, 3, 1, 3, 1],
       [1, 4, 1, 2, 3, 3]], dtype=int64)

In [84]:
rand.integers(low=1, high=25, size=(4,6), endpoint=True)

array([[ 9, 15,  1, 12, 23, 23],
       [ 2,  5, 21,  9, 11,  9],
       [15,  3, 25,  5,  5, 21],
       [22, 23,  4, 21,  8,  9]], dtype=int64)

In [85]:
rand.random((3,2,6))

array([[[0.33184246, 0.98169356, 0.14558932, 0.85498398, 0.72612686,
         0.29459768],
        [0.99199379, 0.58182193, 0.12586769, 0.40152542, 0.59739779,
         0.5498926 ]],

       [[0.62947365, 0.99604402, 0.00903543, 0.83815734, 0.14081536,
         0.41966111],
        [0.0308415 , 0.78620694, 0.00556691, 0.1884903 , 0.97184207,
         0.13570691]],

       [[0.57825528, 0.27131643, 0.29956991, 0.6557206 , 0.62197785,
         0.23200843],
        [0.34302684, 0.89720388, 0.94924315, 0.30795453, 0.24310566,
         0.92773342]]])

In [87]:
arr = np.array([1,2,3,1,1,4,5,2,5,6,7,1])


In [88]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [89]:
np.unique(arr, return_index=True)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  2,  5,  6,  9, 10], dtype=int64))

In [90]:
np.unique(arr, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  2,  5,  6,  9, 10], dtype=int64),
 array([4, 2, 1, 1, 2, 1, 1], dtype=int64))

In [118]:
arr1 = np.array([[1,1,2], [3,3,2], [1,1,2]])


In [119]:
np.unique(arr1)

array([1, 2, 3])

In [120]:
np.unique(arr1, axis=1)

array([[1, 2],
       [3, 2],
       [1, 2]])

In [121]:
np.unique(arr1, axis=0)

array([[1, 1, 2],
       [3, 3, 2]])

In [123]:
org_arr = np.arange(10)
org_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.flip(org_arr)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [135]:
org = np.arange(12).reshape(3,4)
org

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
np.flip(org)

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [137]:
np.flip(org, axis=0)


array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [138]:
np.flip(org, axis=1)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [140]:
np.flip(org[0])

array([3, 2, 1, 0])

In [142]:
np.flip(org[:,2])

array([10,  6,  2])

In [143]:
org.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])